kind: pipeline
name: default

steps:
  - name: testing
    image: golang:1.13.5
    pull: true
    commands:
      - export VERSION=$(git describe --tags --always)
      - go test -race -tags test -coverprofile=coverage.out -covermode=atomic ./...
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN:
        from_secret: my-codecov-token
